[package]
name = "mf_attendance"
version = "0.1.0"
authors = ["alpaca-tc <alpaca-tc@alpaca.tc>"]
edition = "2018"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap" }
anyhow = "1.0.32"
reqwest = { version = "0.10.7", features = ["blocking", "json"] }
chrono = "0.4.13"
